const API_URL = "https://vatis.tech/api/v1";
const API_URL_PATH =
  "/asr-client/auth?service=<service>&model=<model>&language=<language>";

const RESERVATION_URL = "<service_host>/asr/v1/registry/stream/reserve";

const SOCKET_IO_CLIENT_NAMESPACE = "/asr_stream";
const SOCKET_IO_CLIENT_TRANSPORTS = ["websocket"];
const SOCKET_IO_CLIENT_PATH = "/live/transcribe/socket.io";
const SOCKET_IO_CLIENT_RESULT_PATH = "/asr_result";
const SOCKET_IO_CLIENT_REQUEST_PATH = "/asr_request";
const SOCKET_IO_CLIENT_RESPONSE_SPLIT_PACKET = "SplitPacket";
const SOCKET_IO_CLIENT_RESPONSE_FINAL_SPLIT_PACKET = "FinalSplitPacket";
const SOCKET_IO_CLIENT_FRAME_OVERLAP = 0.25;
const SOCKET_IO_CLIENT_BUFFER_OFFSET = 0.25;
const SOCKET_IO_CLIENT_AUDIO_FORMAT = "webm";
const SOCKET_IO_CLIENT_SENDING_HEADERS = "True";

const MICROPHONE_BIT_RATE_SAMPLES = 8000;
const MICROPHONE_TIMESLICE = 250;

const projectConstants = {
  API_URL_PATH,
  API_URL,
  RESERVATION_URL,

  SOCKET_IO_CLIENT_NAMESPACE,
  SOCKET_IO_CLIENT_TRANSPORTS,
  SOCKET_IO_CLIENT_PATH,
  SOCKET_IO_CLIENT_RESULT_PATH,
  SOCKET_IO_CLIENT_REQUEST_PATH,
  SOCKET_IO_CLIENT_RESPONSE_SPLIT_PACKET,
  SOCKET_IO_CLIENT_RESPONSE_FINAL_SPLIT_PACKET,
  SOCKET_IO_CLIENT_FRAME_OVERLAP,
  SOCKET_IO_CLIENT_BUFFER_OFFSET,
  SOCKET_IO_CLIENT_AUDIO_FORMAT,
  SOCKET_IO_CLIENT_SENDING_HEADERS,

  MICROPHONE_BIT_RATE_SAMPLES,
  MICROPHONE_TIMESLICE,
};

export default projectConstants;
