name: Feature request 🔮
description: Please use this if you want something new added 🥳
title: "[Feature]: "
labels: ["feature"]
assignees:
  - einazare
body:
  - type: markdown
    attributes:
      value: |
        In order to make this easy for everyone, please fill in the form bellow.
  - type: textarea
    id: what-problem-does-this-feature-solve
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the end user experience you are trying to build that led to the need for this feature?

        An important design goal of `@vatis-tech/asr-client-js` is keeping the API surface small, straightforward and to help developers use our services using JavaScript more easily. In general, we only consider adding new features that solve a problem that cannot be easily dealt with using existing APIs (i.e. not just an alternative way of doing things that can already be done). The problem should also be common enough to justify the addition.
    validations:
      required: true
  - type: textarea
    id: what-does-the-proposed-api-look-like
    attributes:
      label: What does the proposed API look like?
      description: Describe how you propose to solve the problem and provide code samples of how the API would work once implemented. Note that you can use Markdown to format your code blocks.
    validations:
      required: true
